#!/usr/bin/python3
# coding: utf-8

import re
import json
import urllib.request


RE_FUND_INFO = re.compile('jsonpgz\((.*)\)')

def get_info(fid):
    with urllib.request.urlopen('http://fundgz.1234567.com.cn/js/%s.js' % fid) as f:
        content = f.read().decode('utf-8')
        match = RE_FUND_INFO.match(content)
        if match:
            data_str = match.group(1)
            data = json.loads(data_str)
            name = data['name']
            gszzl = data['gszzl']
            return dict(name=name, gszzl=gszzl)

if __name__ == "__main__":
    infos = []
    d_000311 = get_info('000311')
    d_000478 = get_info('110003')
    d_110022 = get_info('110022')
    for d in [d_000311, d_000478, d_110022]:
        infos.append('{name}:{gszzl}'.format(name=d['name'][0], gszzl=d['gszzl']))
    print(' '.join(infos))
    print(' '.join(infos))
