[tools]
"aqua:atuinsh/atuin" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
go = "1.24"
hugo = "latest"
lazygit = "latest"
neovim = "latest"
node = "22"
python = "3.12"
rg = "latest"
ruby = "3.4.2"
usage = "latest"
yq = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
